### ISSUE TITLE
Cygwin Install

### ISSUE THREAD

**Issue by SwimmingLink** [PiaCarrot/pokeorange#154]
The INSTALL.md for building on Windows in Cygwin states that the package "python" is needed. The Cygwin Setup is telling me that "python" has been obsoleted by "python2". Is the original "python" package actually needed, or are we good to just use "python2" like Cygwin wants us to?

**Comment by BloodlessNS** [comment]
> The INSTALL.md for building on Windows in Cygwin states that the package "python" is needed. The Cygwin Setup is telling me that "python" has been obsoleted by "python2". Is the original "python" package actually needed, or are we good to just use "python2" like Cygwin wants us to?

This isn't the place for such issues (questions like this should be asked in the disord server, or the pret discord server), filing issues is for bug reports. The install instructions do need updating to be honest though. Yes you need python2 and possibly python3. Another thing to note is that you need the most recent RGBDS, not the older one listed

**Comment by PiaCarrot** [comment]
I would follow the install.md on the original pokecrystal repo, these are highly outdated and I'm going to update it eventually.
