### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by JekPasan** [PiaCarrot/pokeorange#169]
I tried running the make command in the terminal, but it outputs:

`gcc -O3 -flto -std=c11 -o tools/lzcomp tools/lz/global.c tools/lz/main.c tools/lz/merging.c tools/lz/mpcomp.c tools/lz/nullcomp.c tools/lz/options.c tools/lz/output.c tools/lz/packing.c tools/lz/repcomp.c tools/lz/spcomp.c tools/lz/uncomp.c tools/lz/util.c
gcc -O3 -o tools/scan_includes tools/scan_includes.c

sort pokeorange.sym -o pokeorange.sym
Input file specified two times.

make: *** [Makefile:65: orange] Error 1`

I installed exactly the 0.5.2 version of rgbds, but neither that nor newer versions work.

P.S.: i run windows 10 64 bits

**Comment by Sukiyami** [comment]
Is this using WSL or Cygwin?

**Comment by Sukiyami** [comment]
@PiaCarrot you may as well close this issue, the makefile is fine and I'm assuming they have the issue their end fixed by now given the lack of response
